from discord.app_commands import Choice

WEBPAGE_CHOICES: tuple[Choice[str], ...] = [
    Choice(name="Home", value=""),
    Choice(name="Getting started", value="getting-started/"),
    Choice(name="Resources", value="resources/"),
    Choice(name="Projects", value="projects/"),
    Choice(name="Rules", value="rules/"),
    Choice(name="Code Adventure", value="code-adventure/"),
    Choice(name="Learning path", value="resources/learning-path/"),
    Choice(name="Codeblocks", value="rules/channels/#__tabbed_2_1"),
]

LATEX_COLORS = {
    "emerald": "Emerald",
    "violet": "Violet",
    "blueviolet": "BlueViolet",
    "skyblue": "SkyBlue",
    "wildstrawberry": "WildStrawberry",
    "red": "Red",
    "periwinkle": "Periwinkle",
    "sepia": "Sepia",
    "magenta": "Magenta",
    "peach": "Peach",
    "cyan": "Cyan",
    "bluegreen": "BlueGreen",
    "orangered": "OrangeRed",
    "limegreen": "LimeGreen",
    "royalpurple": "RoyalPurple",
    "fuchsia": "Fuchsia",
    "teal": "Teal",
    "cornflowerblue": "CornflowerBlue",
    "turquoise": "Turquoise",
    "yelloworange": "YellowOrange",
    "mulberry": "Mulberry",
    "white": "White",
    "violetred": "VioletRed",
    "brown": "Brown",
    "redviolet": "RedViolet",
    "tealblue": "TealBlue",
    "green": "Green",
    "navyblue": "NavyBlue",
    "tan": "Tan",
    "carnationpink": "CarnationPink",
    "burntorange": "BurntOrange",
    "maroon": "Maroon",
    "goldenrod": "Goldenrod",
    "orchid": "Orchid",
    "rubinered": "RubineRed",
    "processblue": "ProcessBlue",
    "olivegreen": "OliveGreen",
    "yellowgreen": "YellowGreen",
    "salmon": "Salmon",
    "junglegreen": "JungleGreen",
    "rawsienna": "RawSienna",
    "thistle": "Thistle",
    "greenyellow": "GreenYellow",
    "melon": "Melon",
    "pinegreen": "PineGreen",
    "lavender": "Lavender",
    "aquamarine": "Aquamarine",
    "springgreen": "SpringGreen",
    "darkred": "DarkRed",
    "darkblue": "DarkBlue",
    "forestgreen": "ForestGreen",
    "darkorchid": "DarkOrchid",
    "orange": "Orange",
    "yellow": "Yellow",
    "royalblue": "RoyalBlue",
    "gray": "Gray",
    "midnightblue": "MidnightBlue",
    "redorange": "RedOrange",
    "darkorange": "DarkOrange",
    "cadetblue": "CadetBlue",
    "cerulean": "Cerulean",
    "apricot": "Apricot",
    "mahogany": "Mahogany",
    "bittersweet": "Bittersweet",
    "blue": "Blue",
    "purple": "Purple",
    "darkgreen": "DarkGreen",
    "plum": "Plum",
    "dandelion": "Dandelion",
    "seagreen": "SeaGreen",
    "black": "Black",
    "brickred": "BrickRed",
}
