FROM python:3.10.13-slim-bookworm
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY /bot .
# Not needed until adding voice. Until then, much faster without
# RUN apt-get update && apt-get install -y ffmpeg
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "__main__.py"]