FROM postgres:17.5-alpine3.21

COPY /db/init.sql /docker-entrypoint-initdb.d/
COPY /db/entrypoint.sh /usr/local/bin/
COPY /db/migrations.sql /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
CMD ["postgres"]
