FROM python:3.11.9

WORKDIR /api

COPY /api /api
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /api/requirements-api.txt

EXPOSE 5000
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
